spring:
  application:
    name: spring-security
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEA1XIpaAmDv/XkckupdxMnNYFyeY/E995LkGV7J8ipFIOu3bcK3TOPEUziZnJSC}
      expiration: ${JWT_EXPIRATION:86400000} # a day
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:spring_security}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
